#!/usr/bin/env node
/**
 * Install the parts of vibecosystem that install-codex.sh deliberately leaves
 * out: agent definitions, rules, and (optionally) the hook chain.
 *
 * Skills are NOT handled here - use install-codex.sh for those.
 *
 * Rules are split rather than concatenated. A single AGENTS.md holding every
 * rule would sit in the context of every request; Codex loads a skill only when
 * its description matches, so long procedural rules become skills and only the
 * short always-on ones are inlined.
 *
 * Usage:
 *   node tools/codex-extras.mjs [--agents] [--rules] [--hooks] [--all]
 *                               [--dry-run] [--force]
 *                               [--codex-home DIR] [--skills-home DIR]
 */
import { createHash } from 'node:crypto';
import {
  cpSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync,
  rmSync, writeFileSync,
} from 'node:fs';
import { homedir } from 'node:os';
import { basename, dirname, isAbsolute, join, relative, resolve } from 'node:path';

const GENERATED_MARKER = '# Generated by vibecosystem Codex agent mirror: ';
const AGENTS_MD_MARKER = '# vibecosystem';
const RULE_SKILL_MARKER = '<!-- codex-adapted-skill: vibecosystem-rule -->';
const GENERATED_HOOK_MARKER = '// Generated by vibecosystem';
const REGISTRY_START = '# BEGIN vibecosystem agent roles';
const REGISTRY_END = '# END vibecosystem agent roles';
const CORE_MAX_BYTES = 4096;

const REPO = resolve(dirname(new URL(import.meta.url).pathname), '..');
const argv = process.argv.slice(2);
const flag = (name) => argv.includes(`--${name}`);
const opt = (name, fallback) => {
  const i = argv.indexOf(`--${name}`);
  return i > -1 ? argv[i + 1] : fallback;
};

const ALL = flag('all');
const DRY = flag('dry-run');
const FORCE = flag('force');
const CODEX_HOME = opt('codex-home', process.env.CODEX_HOME || join(homedir(), '.codex'));
const SKILLS_HOME = opt('skills-home', join(homedir(), '.agents', 'skills'));
const CLAUDE_AGENTS = opt('claude-agents', join(homedir(), '.claude', 'agents'));
const CLAUDE_SETTINGS = opt('claude-settings', join(homedir(), '.claude', 'settings.json'));
const BACKUP_ROOT = join(dirname(SKILLS_HOME), 'vibecosystem-backups');
let BACKUP_DIR = '';
let BACKUP_PLANNED = false;
const BACKED_UP_PATHS = new Set();

const ALWAYS_ON_RULES = new Map([
  ['claim-verification', 'Codebase hakkında varlık/yokluk/davranış iddiası kurarken grep sonucunu kanıt sayma; iddia ettiğin yolu OKU, akışı izle ve kanıtı dosya:satır ile ver. Detay: `$rule-claim-verification`.'],
  ['coding-style', 'Kod yazarken mevcut objeyi mutate etme veya büyük karma-sorumluluklu modül üretme; proje pattern’inin kanıtını oku, küçük odaklı birimler ve açık hata/validation akışı yaz. Detay: `$rule-coding-style`.'],
  ['safety-and-quality', 'Dosya/sistem/git/security etkili işlemde hedefi doğrulamadan silme, overwrite etme veya onay gerektiren mutation’ı çalıştırma; önce scope’u oku, güvenli uygulamayı yap ve ilgili gate’leri koş. Detay: `$rule-safety-and-quality`.'],
  ['commit-pr-linear-conventions', 'Commit/push/reset/checkout/clean/stash/rebase/merge, branch veya PR işinde açık eylem-başı onay olmadan mutation yapma ve AI attribution/test-plan boilerplate üretme; proje talimatını oku, diff’i sınırla ve formatı uygula. Detay: `$rule-commit-pr-linear-conventions`.'],
  ['user-action-items', 'Kullanıcının tek başına yapabileceği iş varsa onu cevap içine gömüp kaybetme veya kırmızı daireyi başka anlamda kullanma; aksiyonları cevabın en sonunda tek numaralı SENDE/YOUR TURN bloğunda topla, yoksa blok yazma. Detay: `$rule-user-action-items`.'],
  ['research-confidence', 'Bilinmeyen codebase’de ilgili dosya, akış, pattern ve dependency bilgisi %90’a ulaşmadan implementasyona başlama; entry point, bağımlılık ve testleri hedefli oku, kalan spesifik boşlukları kapat. Detay: `$rule-research-confidence`.'],
  ['architecture-principles', 'Yapısal değişiklikte yukarı bağımlılık, UI+logic karışımı veya plansız structural churn üretme; proje konvansiyonlarını oku, katman/SRP sınırlarını planla ve her fazı build/test kapısıyla kapat. Detay: `$rule-architecture-principles`.'],
  ['pre-implementation-contract', 'Kod değişikliğinde gerekli sözleşme kademesi onaylanmadan implementasyona başlama; ilgili kod/config/testleri oku, Goal + blocking soru + varsayım + dosya-bazlı planı gereken kapsamda sun ve onayı bekle. Detay: `$rule-pre-implementation-contract`.'],
  ['hizir-identity', 'Her etkileşimde kurulmamış agent/skill/hook veya sabit envanter sayısı üretme; Türkçe, kısa ve dürüst çalış, runtime envanterini oku ve yalnız bulunan yüzeyleri kullan. Detay: `$rule-hizir-identity`.'],
]);
const EXCLUDED_RULES = new Set(['council']);
const REQUIRED_RULE_OVERRIDES = new Set([
  'agent-assignment-matrix', 'agent-error-reporting', 'agents',
  'architecture-principles', 'auto-skill-activation', 'canavar',
  'claim-verification', 'collaborative-decisions',
  'commit-pr-linear-conventions', 'cross-project-learning',
  'hizir-identity', 'hooks', 'incremental-writing', 'memory-system',
  'performance', 'phantom-mindset', 'pre-compact-state',
  'pre-implementation-contract', 'proactive-delegation', 'qa-loop',
  'safety-and-quality', 'vibecosystem-welcome', 'worktree-handoff',
]);

const EXCLUDED_AGENTS = new Set([
  'compass', 'council-blast-radius', 'council-chair',
  'council-empiricist', 'council-inventory', 'council-refuter',
  'council-simplifier', 'cost-tracker', 'maestro', 'memory-extractor',
  'psyche', 'reputation-engine', 'scribe', 'self-learner',
  'session-replay-analyzer', 'swarm-optimizer',
]);
const REQUIRED_AGENT_OVERRIDES = new Set([
  'browser-agent', 'mcp-manager', 'review-agent', 'strategist',
  'website-cloner',
]);

const CODEX_HOOK_ALLOWLIST = Object.freeze([
  Object.freeze({
    event: 'PreToolUse',
    sourceMatcher: '',
    matcher: '^Bash$',
    handler: 'credential-deny',
  }),
]);
const FORBIDDEN_HOOK_EVENTS = new Set(['PermissionRequest']);

function timestamp() {
  const now = new Date();
  const pad = (value) => String(value).padStart(2, '0');
  return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
}

function assertRegularTarget(path) {
  if (!existsSync(path)) return;
  const stat = lstatSync(path);
  if (stat.isSymbolicLink()) throw new Error(`refusing to overwrite symlink: ${path}`);
  if (!stat.isFile()) throw new Error(`write target is not a regular file: ${path}`);
}

function isWithin(base, path) {
  const rel = relative(resolve(base), resolve(path));
  return rel === '' || (!rel.startsWith('..') && !isAbsolute(rel));
}

function backupLabel(path) {
  if (isWithin(CODEX_HOME, path)) return join('codex', relative(resolve(CODEX_HOME), resolve(path)));
  if (isWithin(SKILLS_HOME, path)) return join('skills', relative(resolve(SKILLS_HOME), resolve(path)));
  throw new Error(`refusing to back up path outside managed roots: ${path}`);
}

function ensureBackupDirectory() {
  if (DRY || BACKUP_DIR) return;
  if (existsSync(BACKUP_ROOT)) {
    const stat = lstatSync(BACKUP_ROOT);
    if (stat.isSymbolicLink()) throw new Error(`refusing to use symlink backup root: ${BACKUP_ROOT}`);
    if (!stat.isDirectory()) throw new Error(`backup root is not a directory: ${BACKUP_ROOT}`);
  }
  mkdirSync(BACKUP_ROOT, { recursive: true });
  const stem = `${timestamp()}-${process.pid}`;
  let candidate = join(BACKUP_ROOT, stem);
  let suffix = 0;
  while (existsSync(candidate)) {
    suffix += 1;
    candidate = join(BACKUP_ROOT, `${stem}-${suffix}`);
  }
  mkdirSync(candidate);
  BACKUP_DIR = candidate;
}

function backupExistingPath(path) {
  if (!existsSync(path)) return;
  const absolute = resolve(path);
  if (BACKED_UP_PATHS.has(absolute)) return;
  const stat = lstatSync(path);
  if (stat.isSymbolicLink()) throw new Error(`refusing to back up symlink: ${path}`);
  const label = backupLabel(path);
  BACKUP_PLANNED = true;
  BACKED_UP_PATHS.add(absolute);
  if (DRY) return;
  ensureBackupDirectory();
  let candidate = join(BACKUP_DIR, label);
  let suffix = 0;
  mkdirSync(dirname(candidate), { recursive: true });
  while (existsSync(candidate)) {
    suffix += 1;
    candidate = `${join(BACKUP_DIR, label)}.${suffix}`;
  }
  cpSync(path, candidate, { recursive: true, preserveTimestamps: true });
}

function hasOwnershipMarker(body, marker, mode) {
  if (!marker) return true;
  return mode === 'includes' ? body.includes(marker) : body.startsWith(marker);
}

function assertWritable(path, { marker = '', markerMode = 'startsWith' } = {}) {
  if (!existsSync(path)) return;
  assertRegularTarget(path);
  if (marker && !hasOwnershipMarker(readFileSync(path, 'utf8'), marker, markerMode) && !FORCE) {
    throw new Error(`refusing to overwrite unmanaged file without --force: ${path}`);
  }
}

function write(path, body, options = {}) {
  assertWritable(path, options);
  backupExistingPath(path);
  if (DRY) return;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body);
}

const sha256 = (text) => createHash('sha256').update(text).digest('hex');

function readJson(path, label) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch (error) {
    throw new Error(`${label} is not valid JSON: ${path}: ${error.message}`);
  }
}

function flatMarkdownFiles(dir, label, { ignoreDotfiles = false } = {}) {
  if (!existsSync(dir)) throw new Error(`${label} directory is missing: ${dir}`);
  const entries = readdirSync(dir, { withFileTypes: true })
    .filter((entry) => !(ignoreDotfiles && entry.name.startsWith('.')));
  const invalid = entries.filter((entry) => !entry.isFile() || !entry.name.endsWith('.md'));
  if (invalid.length) {
    throw new Error(`${label} must be flat and contain only .md files: ${invalid.map((entry) => entry.name).join(', ')}`);
  }
  return entries.map((entry) => entry.name).sort();
}

function assertSameSet(actual, expected, label) {
  const missing = [...expected].filter((item) => !actual.has(item));
  const extra = [...actual].filter((item) => !expected.has(item));
  if (missing.length || extra.length) {
    throw new Error(`${label} mismatch; missing=[${missing.join(', ')}] extra=[${extra.join(', ')}]`);
  }
}

function readValidatedOverlays(kind, required, excluded) {
  const canonicalDir = join(REPO, kind);
  const overlayDir = join(canonicalDir, 'codex');
  const baselinePath = join(canonicalDir, 'codex-baseline.json');
  const canonical = new Map(
    readdirSync(canonicalDir, { withFileTypes: true })
      .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
      .map((entry) => {
        const slug = basename(entry.name, '.md');
        return [slug, readFileSync(join(canonicalDir, entry.name), 'utf8')];
      }),
  );
  const overlayFiles = flatMarkdownFiles(overlayDir, `${kind}/codex overlays`);
  const overlays = new Map(overlayFiles.map((file) => [
    basename(file, '.md'),
    readFileSync(join(overlayDir, file), 'utf8'),
  ]));

  for (const slug of overlays.keys()) {
    if (!canonical.has(slug)) throw new Error(`orphan ${kind} Codex override: ${slug}`);
    if (excluded.has(slug)) throw new Error(`excluded ${kind} must not have a Codex override: ${slug}`);
  }
  assertSameSet(new Set(overlays.keys()), required, `${kind} required Codex overrides`);

  const baseline = readJson(baselinePath, `${kind} Codex baseline`);
  if (baseline.schema_version !== 1 || baseline.algorithm !== 'sha256' || !baseline.overrides) {
    throw new Error(`${kind} Codex baseline has an unsupported schema: ${baselinePath}`);
  }
  assertSameSet(new Set(Object.keys(baseline.overrides)), new Set(overlays.keys()), `${kind} baseline entries`);
  for (const [slug, expectedHash] of Object.entries(baseline.overrides)) {
    const actualHash = sha256(canonical.get(slug));
    if (actualHash !== expectedHash) {
      throw new Error(`canonical ${kind}/${slug}.md changed; review ${kind}/codex/${slug}.md and refresh its baseline intentionally`);
    }
  }
  return { canonical, overlays };
}

function splitFrontmatter(text) {
  if (!text.startsWith('---')) return { meta: {}, body: text };
  const end = text.indexOf('\n---', 3);
  if (end === -1) return { meta: {}, body: text };
  const raw = text.slice(4, end);
  const body = text.slice(end + 4).replace(/^\n+/, '');
  const meta = {};
  let key = null;
  for (const line of raw.split('\n')) {
    const m = line.match(/^([a-zA-Z_][\w-]*):\s*(.*)$/);
    if (m) {
      key = m[1];
      meta[key] = m[2].trim().replace(/^["'](.*)["']$/s, '$1');
    } else if (key && /^\s*-\s+/.test(line)) {
      meta[key] = [].concat(meta[key] === '' ? [] : meta[key], line.replace(/^\s*-\s+/, '').trim());
    }
  }
  return { meta, body };
}

/** TOML multi-line string that survives regexes and backslashes in prose. */
function tomlBlock(text) {
  if (!text.includes("'''")) return `'''\n${text}\n'''`;
  return `"""\n${text.replaceAll('\\', '\\\\').replaceAll('"""', '\\"\\"\\"')}\n"""`;
}
const tomlString = (s) => `"${String(s).replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;

// --- agents -----------------------------------------------------------------
const LEAF_CONTRACT = [
  '## Codex leaf-agent contract',
  '',
  'This is a leaf agent. Do not call `spawn_agent`, dispatch another agent, or start background workers.',
  'If another role would help, return the recommended role, bounded task, and evidence needed to the parent context.',
].join('\n');

const T5_LITERAL_SPECS = [
  ['api-designer', 'body', '| api-doc-generator | Dokumantasyon olusturma |', '| technical-writer | Dokumantasyon olusturma |'],
  ['benchmark', 'body', '| profiler/nitro | Detayli profiling sonuclari |', '| profiler | Detayli profiling sonuclari |'],
  ['browser-agent', 'body', '| pathfinder | GitHub repo exploration - navigate READMEs, check issues, extract code |', '| harvest | GitHub repo exploration - navigate READMEs, check issues, extract code |'],
  ['build-error-resolver', 'body', '- Code needs refactoring (use refactor-cleaner)', '- Code needs refactoring (recommend a bounded refactor to the parent)'],
  ['coroner', 'body', "- Öğrenilen ders → self-learner'a aktar", '- Öğrenilen dersi parent context icin raporla'],
  ['coroner', 'body', "8. Ogrenilen dersi self-learner'a aktar", '8. Ogrenilen dersi parent context icin raporla'],
  ['coroner', 'body', '- **self-learner:** Ogrenilen ders → kural olarak kaydet', '- **Parent context:** Ogrenilen ders icin kural onerisi dondur'],
  ['coroner', 'body', '- **canavar:** Hata bilgisini tum ekibe yay (error-ledger)', '- **Parent context:** Hata bilgisini ve etki alanini raporla'],
  ['coroner', 'body', "- [ ] Ogrenilen ders self-learner'a aktarildi", '- [ ] Ogrenilen ders parent context icin raporlandi'],
  ['graph-analyst', 'description', 'pathfinder→harvest (external repo)', 'harvest (external repo)'],
  ['graph-analyst', 'body', '- **refactor-cleaner**: Circular deps feed refactoring plan', '- **planner**: Circular deps feed refactoring plan'],
  ['harvest', 'body', '| pathfinder | Deep crawl external repos (README, docs, examples) |', '| oracle | Deep crawl external repos (README, docs, examples) |'],
  ['incident-responder', 'body', "| self-learner | Incident'tan ogrenim |", "| coroner | Incident'tan ogrenim |"],
  ['incident-responder', 'body', '| compass | Incident timeline kaydi |', '| parent context | Incident timeline kaydi |'],
  ['janitor', 'body', '| psyche | Monitor cleanup fatigue | Long cleanup sessions trigger psyche intervention |', '| parent context | Monitor cleanup fatigue | Report long cleanup sessions |'],
  ['janitor', 'body', '| maestro | Integrate cleanup tasks into sprint plan | Weekly cleanup backlog |', '| project-manager | Integrate cleanup tasks into sprint plan | Weekly cleanup backlog |'],
  ['mcp-manager', 'body', '| compass | Session basinda MCP durum ozeti |', '| parent context | Session basinda MCP durum ozeti |'],
  ['planner', 'description', 'maestro (plan execution orchestration)', 'parent context (plan execution coordination)'],
  ['planner', 'body', "- Mark phases that can run in parallel (different agents, non-overlapping files) — this feeds maestro's `parallel_group`", '- Mark phases that can run in parallel only as a recommendation to the parent context'],
  ['project-manager', 'description', 'maestro (agent orchestration)', 'parent context (agent coordination)'],
  ['sast-scanner', 'body', '- **self-learner agent:** Learns from recurring SAST findings', '- **Parent context:** Receives recurring SAST findings and proposed prevention rules'],
  ['scout', 'description', 'pathfinder→harvest (external repo)', 'harvest (external repo)'],
  ['shipper', 'body', 'description: "Her PR için herald-style özet yazar"', 'description: "Her PR için release özeti yazar"'],
  ['shipper', 'body', 'description: "PR için herald özeti yaz"', 'description: "PR için release özeti yaz"'],
  ['shipper', 'body', '  compass_sync:', '  context_sync:'],
  ['shipper', 'body', '  maestro_sync:', '  planning_sync:'],
  ['strategist', 'description', 'maestro (orchestration)', 'parent context (coordination)'],
  ['verifier', 'body', "4. Fail durumunda CLAUDE.md'ye not ekle (self-learner'a bildir)", "4. Fail durumunda AGENTS.md'yi degistirme; kaniti parent context'e bildir"],
];

const T6_LITERAL_SPECS = [
  ['agentica-agent', 'body', 'cat $CLAUDE_PROJECT_DIR/.claude/skills/agentica-sdk/SKILL.md', 'Load `$agentica-sdk` through Codex skill discovery before using its procedure.'],
  ['architect', 'body', '- **Implementation agent roster**: which agents will build each component — map components to agents via `~/.claude/rules/agent-assignment-matrix.md` (e.g. API → backend-dev, UI → frontend-dev, infra → devops, auth QA → security-reviewer). Verify names exist in `~/.claude/agents/`. This roster is consumed by planner (step breakdown) and maestro (orchestration directive)', '- **Implementation agent roster**: read `~/.codex/agents/*.toml`, use only installed roles, and return any execution/delegation recommendation to the parent context. If the roster is empty, keep the work in the parent context.'],
  ['liaison', 'body', '**ALWAYS write review to:**\n```\n$CLAUDE_PROJECT_DIR/.claude/cache/agents/liaison/output-{timestamp}.md\n```', '**Return the review directly to the parent context; do not write a cache file.**'],
  ['planner', 'body', '- Source of truth: `~/.claude/rules/agent-assignment-matrix.md` (task kategorisi → Ana Agent | Yedek | QA Agent)', '- Source of truth: `$rule-agent-assignment-matrix` plus the installed `~/.codex/agents/*.toml` roster'],
  ['planner', 'body', '- Verify each agent name exists in `~/.claude/agents/` (exact filename match) before assigning', '- Verify each role has an installed `~/.codex/agents/<slug>.toml`; if not, keep that work in the parent context'],
];

function normalizeAgentSource(text) {
  return text.replace(/\r\n/g, '\n').replaceAll('-Users-svoboden', '<project-slug>');
}

function applyLiteralSpecs(slug, parts, specs, label) {
  const next = { ...parts, meta: { ...parts.meta } };
  for (const [targetSlug, field, needle, replacement] of specs) {
    if (targetSlug !== slug) continue;
    const source = field === 'description' ? String(next.meta.description || '') : next.body;
    const matches = source.split(needle).length - 1;
    if (matches !== 1) {
      throw new Error(`${label} ${slug}.${field} expectedMatches=1, observed=${matches}: ${needle}`);
    }
    if (field === 'description') next.meta.description = source.replace(needle, replacement);
    else next.body = source.replace(needle, replacement);
  }
  return next;
}

function stripWorktreeProtocol(text) {
  const lines = text.split('\n');
  const kept = [];
  let skipping = false;
  for (const line of lines) {
    if (/^##\s+(?:Worktree Handoff|GIT WORKTREE PROTOKOLU)\b/i.test(line)) {
      skipping = true;
      continue;
    }
    if (skipping && /^#{1,2}\s+/.test(line)) skipping = false;
    if (!skipping && !/\bisolation:\s*worktree\b/i.test(line)) kept.push(line);
  }
  return kept.join('\n');
}

function adaptCodexPaths(text) {
  let adapted = text
    .replace(/^\$CLAUDE_PROJECT_DIR\s*=.*$/gm, 'Project root: current working directory (`$PWD`).')
    .replaceAll('$CLAUDE_PROJECT_DIR', '$PWD')
    .replace(/~\/\.claude\/rules\/([\w-]+)\.md/g, '~/.agents/skills/rule-$1/SKILL.md')
    .replaceAll('~/.claude/agents/', '~/.codex/agents/')
    .replaceAll('CLAUDE.md', 'AGENTS.md')
    .replaceAll('parent Claude', 'parent context')
    .replaceAll('Parent Claude', 'Parent context')
    .replaceAll('Claude Code', 'Codex');
  adapted = adapted.split('\n').filter((line) => {
    if (/\.claude\//.test(line)) return false;
    if (/<project-slug>/.test(line)) return false;
    return true;
  }).join('\n');
  return adapted.replace(/\n{3,}/g, '\n\n').trim();
}

function mechanicalAgentTransform(parts) {
  const meta = { description: String(parts.meta.description || '').trim() };
  let body = adaptCodexPaths(stripWorktreeProtocol(parts.body));
  if (!body.includes('## Codex leaf-agent contract')) body = `${body}\n\n${LEAF_CONTRACT}`;
  return { meta, body: body.trim() };
}

function assertAgentTransformIdempotent(slug, transformed) {
  const second = mechanicalAgentTransform(transformed);
  if (second.meta.description !== transformed.meta.description || second.body !== transformed.body) {
    throw new Error(`Codex agent transform is not idempotent for ${slug}`);
  }
}

function personaNickname(slug, description) {
  const matches = [...description.matchAll(/\(([^(),]+?) persona\)/gu)];
  if (matches.length > 1) throw new Error(`agent ${slug} has multiple persona names in its description`);
  if (!matches.length) return null;
  const nickname = matches[0][1].trim();
  if (!nickname || !nickname.includes(' ')) {
    throw new Error(`agent ${slug} has an invalid persona name in its description: ${nickname}`);
  }
  return nickname;
}

function validateLiveAgentMirror(canonical) {
  const liveFiles = flatMarkdownFiles(CLAUDE_AGENTS, 'live Claude agents', { ignoreDotfiles: true });
  if (liveFiles.length !== 131) throw new Error(`expected 131 live Claude agents, found ${liveFiles.length}`);
  for (const file of liveFiles) {
    const slug = basename(file, '.md');
    if (!canonical.has(slug)) throw new Error(`live Claude agent has no canonical repo source: ${slug}`);
    const live = normalizeAgentSource(readFileSync(join(CLAUDE_AGENTS, file), 'utf8'));
    const repo = normalizeAgentSource(canonical.get(slug));
    if (live !== repo) throw new Error(`live Claude agent differs from canonical content beyond project placeholder: ${slug}`);
  }
  return liveFiles;
}

function managedAgentRegistry(agents) {
  const lines = [
    REGISTRY_START,
    '[agents]',
    'max_concurrent_threads_per_session = 4',
    'max_depth = 1',
  ];
  for (const agent of agents) {
    const roleLines = [
      '',
      `[agents.${agent.role}]`,
      `description = ${tomlString(agent.description)}`,
      `config_file = ${tomlString(`agents/${agent.slug}.toml`)}`,
    ];
    if (agent.nickname) roleLines.push(`nickname_candidates = [${tomlString(agent.nickname)}]`);
    lines.push(...roleLines);
  }
  lines.push(REGISTRY_END);
  return `${lines.join('\n')}\n`;
}

function prepareAgentRegistry(agents) {
  const configPath = join(CODEX_HOME, 'config.toml');
  assertRegularTarget(configPath);
  const before = existsSync(configPath) ? readFileSync(configPath, 'utf8') : '';
  const start = before.indexOf(REGISTRY_START);
  const end = before.indexOf(REGISTRY_END);
  if ((start === -1) !== (end === -1)) throw new Error('Codex agent registry markers are incomplete in config.toml');
  let base = before;
  if (start !== -1) base = `${before.slice(0, start)}${before.slice(end + REGISTRY_END.length)}`;
  if (/^\s*\[agents(?:\.|\])/m.test(base)) {
    throw new Error('config.toml already has an unmanaged [agents] block; merge it explicitly before installing the mirror');
  }
  const combined = `${base.trimEnd()}${base.trim() ? '\n\n' : ''}${managedAgentRegistry(agents)}`;
  return { path: configPath, body: combined };
}

function installAgents() {
  const { canonical, overlays } = readValidatedOverlays('agents', REQUIRED_AGENT_OVERRIDES, EXCLUDED_AGENTS);
  const liveFiles = validateLiveAgentMirror(canonical);
  const dest = join(CODEX_HOME, 'agents');
  const agents = [];
  const outputs = [];

  for (const file of liveFiles) {
    const slug = basename(file, '.md');
    if (EXCLUDED_AGENTS.has(slug)) continue;
    let sourceParts = splitFrontmatter(normalizeAgentSource(readFileSync(join(CLAUDE_AGENTS, file), 'utf8')));
    sourceParts = applyLiteralSpecs(slug, sourceParts, T5_LITERAL_SPECS, 'T5');
    sourceParts = applyLiteralSpecs(slug, sourceParts, T6_LITERAL_SPECS, 'T6');
    const selectedParts = overlays.has(slug) ? splitFrontmatter(overlays.get(slug)) : sourceParts;
    const transformed = mechanicalAgentTransform(selectedParts);
    assertAgentTransformIdempotent(slug, transformed);
    if (!transformed.meta.description) throw new Error(`agent ${slug} has no description after transformation`);
    if (/\.claude\/|<project-slug>|\bisolation:\s*worktree\b/i.test(`${transformed.meta.description}\n${transformed.body}`)) {
      throw new Error(`agent ${slug} retains a Claude-only path or worktree runtime claim`);
    }

    const role = slug.replaceAll('-', '_');
    const lines = [
      `${GENERATED_MARKER}${slug}; edit the live source or repo Codex overlay, not this file.`,
      `name = ${tomlString(role)}`,
      `description = ${tomlString(transformed.meta.description)}`,
      `developer_instructions = ${tomlBlock(transformed.body)}`,
    ];
    outputs.push({ path: join(dest, `${slug}.toml`), body: `${lines.join('\n')}\n` });
    agents.push({
      slug,
      role,
      description: transformed.meta.description,
      nickname: personaNickname(slug, transformed.meta.description),
    });
  }

  const nicknameCount = agents.filter((agent) => agent.nickname).length;
  if (nicknameCount !== 16) throw new Error(`expected 16 persona nicknames, found ${nicknameCount}`);

  const registry = prepareAgentRegistry(agents);
  for (const output of outputs) assertWritable(output.path, { marker: GENERATED_MARKER });
  assertWritable(registry.path);
  for (const output of outputs) write(output.path, output.body, { marker: GENERATED_MARKER });
  write(registry.path, registry.body);

  if (!DRY && existsSync(dest)) {
    const selected = new Set(agents.map((agent) => `${agent.slug}.toml`));
    for (const file of readdirSync(dest).filter((name) => name.endsWith('.toml'))) {
      const path = join(dest, file);
      if (lstatSync(path).isSymbolicLink()) continue;
      if (!selected.has(file) && readFileSync(path, 'utf8').startsWith(GENERATED_MARKER)) {
        backupExistingPath(path);
        rmSync(path);
      }
    }
  }
  return { count: agents.length, overrides: overlays.size, excluded: EXCLUDED_AGENTS.size };
}

// --- rules ------------------------------------------------------------------
function firstMeaningfulLine(body) {
  for (const line of body.split('\n')) {
    const t = line.trim();
    if (!t || t.startsWith('#') || t.startsWith('>')) continue;
    return t.replace(/[*`]/g, '').slice(0, 180);
  }
  return '';
}

function installRules() {
  const { canonical, overlays } = readValidatedOverlays('rules', REQUIRED_RULE_OVERRIDES, EXCLUDED_RULES);
  const asSkills = [...canonical.keys()]
    .filter((slug) => !EXCLUDED_RULES.has(slug))
    .sort()
    .map((slug) => ({ slug, text: overlays.get(slug) || canonical.get(slug) }));
  if (asSkills.length !== 26) throw new Error(`expected 26 Codex rule skills, found ${asSkills.length}`);

  const ruleOutputs = asSkills.map(({ slug, text }) => {
    const title = text.match(/^#\s+(.+)$/m)?.[1] || slug;
    const summary = firstMeaningfulLine(text) || title;
    const description = `${title} - ${summary} Apply when the task touches this area.`;
    const front = `---\nname: rule-${slug}\ndescription: ${JSON.stringify(description)}\n---\n\n${RULE_SKILL_MARKER}\n\n`;
    return { path: join(SKILLS_HOME, `rule-${slug}`, 'SKILL.md'), body: front + text };
  });

  const core = [
    '# vibecosystem',
    '',
    'Always-on Codex guardrails. Each line states the trigger, hard prohibition, positive action, and full procedure skill.',
    '',
    ...[...ALWAYS_ON_RULES].map(([slug, text]) => `- **${slug}:** ${text}`),
    '',
  ].join('\n');
  for (const slug of ALWAYS_ON_RULES.keys()) {
    if (!asSkills.some((rule) => rule.slug === slug)) throw new Error(`always-on rule has no full rule skill: ${slug}`);
  }
  const bytes = Buffer.byteLength(core);
  if (bytes > CORE_MAX_BYTES) throw new Error(`generated AGENTS.md is ${bytes} bytes; CORE_MAX_BYTES=${CORE_MAX_BYTES}`);
  const agentsPath = join(CODEX_HOME, 'AGENTS.md');
  assertWritable(agentsPath, { marker: AGENTS_MD_MARKER });
  for (const output of ruleOutputs) {
    assertWritable(output.path, { marker: RULE_SKILL_MARKER, markerMode: 'includes' });
  }
  write(agentsPath, core, { marker: AGENTS_MD_MARKER });
  for (const output of ruleOutputs) {
    write(output.path, output.body, { marker: RULE_SKILL_MARKER, markerMode: 'includes' });
  }
  return { inline: ALWAYS_ON_RULES.size, skills: asSkills.length, bytes, overrides: overlays.size };
}

// --- hooks ------------------------------------------------------------------
function hookName(command) {
  return String(command || '').match(/(?:^|[/\\])([\w.-]+)\.mjs(?:["']?\s|["']?$)/)?.[1] || null;
}

function validateCredentialHandlerSource(source) {
  const forbiddenEffects = [
    /\b(?:writeFile|writeFileSync|appendFile|appendFileSync)\b/,
    /node:child_process|from\s+["']child_process["']|\bexecFile?Sync?\s*\(|\bspawnSync?\s*\(/,
    /\b(?:WebSocket|fetch)\s*\(|node:(?:net|http|https)/,
  ];
  if (forbiddenEffects.some((pattern) => pattern.test(source))) {
    throw new Error('credential-deny gained a write, process-spawn, or network side effect; allowlist review required');
  }
  if (!/readFileSync\(0/.test(source) || !/decision:\s*["']block["']/.test(source)) {
    throw new Error('credential-deny no longer has the empirically verified stdin + block contract');
  }
  if (/(?:permissionDecision|behavior)\s*:\s*["']allow["']/i.test(source)) {
    throw new Error('credential-deny must never auto-approve a permission request');
  }
  if (/\.claude\//.test(source)) throw new Error('credential-deny retains a Claude-only path');
}

function validateCodexHooks(document, handlerSource) {
  const events = Object.keys(document.hooks || {});
  if (events.length !== 1 || events[0] !== 'PreToolUse') throw new Error('Codex hook output must contain only PreToolUse');
  const matchers = document.hooks.PreToolUse;
  if (!Array.isArray(matchers) || matchers.length !== 1 || matchers[0].matcher !== '^Bash$') {
    throw new Error('Codex credential-deny must use the exact ^Bash$ PreToolUse matcher');
  }
  const handlers = matchers[0].hooks;
  if (!Array.isArray(handlers) || handlers.length !== 1 || handlers[0].type !== 'command') {
    throw new Error('Codex hook output must contain exactly one command handler');
  }
  const serialized = `${JSON.stringify(document)}\n${handlerSource}`;
  if (/PermissionRequest|rtk\s+hook\s+claude|dashboard-ws-emitter/i.test(serialized)) {
    throw new Error('Codex hook output contains a forbidden event or handler');
  }
  if (/dangerously.*hook.*trust/i.test(serialized)) throw new Error('Codex hook output attempts to bypass hook trust');
  if (/trusted_hash/.test(serialized)) throw new Error('the installer must not grant hook trust');
  validateCredentialHandlerSource(handlerSource);
}

function installHooks() {
  const settings = readJson(CLAUDE_SETTINGS, 'live Claude settings');
  const sourceHooks = settings.hooks || {};
  for (const event of FORBIDDEN_HOOK_EVENTS) {
    if ((sourceHooks[event] || []).length) {
      throw new Error(`${event} matchers are hard-refused by the Codex hook generator`);
    }
  }

  const registered = Object.values(sourceHooks).flatMap((matchers) => matchers || [])
    .reduce((sum, matcher) => sum + (matcher.hooks || []).length, 0);
  const selected = [];
  for (const allowed of CODEX_HOOK_ALLOWLIST) {
    if (FORBIDDEN_HOOK_EVENTS.has(allowed.event)) throw new Error(`forbidden hook event in allowlist: ${allowed.event}`);
    const matches = (sourceHooks[allowed.event] || []).flatMap((matcher) =>
      matcher.matcher === allowed.sourceMatcher
        ? (matcher.hooks || []).filter((handler) => hookName(handler.command) === allowed.handler)
        : []);
    if (matches.length !== 1) {
      throw new Error(`allowlisted ${allowed.event}/${allowed.handler} expected exactly once in live settings, found ${matches.length}`);
    }
    selected.push({ allowed, source: matches[0] });
  }
  if (selected.length !== 1) throw new Error(`expected one allowlisted Codex handler, found ${selected.length}`);

  const sourceCommand = String(selected[0].source.command);
  const sourcePath = sourceCommand.match(/(?:^|\s)(?:"([^"]*credential-deny\.mjs)"|'([^']*credential-deny\.mjs)'|(\S*credential-deny\.mjs))(?:\s|$)/);
  const handlerSourcePath = sourcePath && (sourcePath[1] || sourcePath[2] || sourcePath[3]);
  if (!handlerSourcePath || !existsSync(handlerSourcePath)) {
    throw new Error(`cannot resolve allowlisted credential-deny source from command: ${sourceCommand}`);
  }
  const handlerSource = readFileSync(handlerSourcePath, 'utf8').replace(/\r\n/g, '\n');
  validateCredentialHandlerSource(handlerSource);

  const handlerDest = join(CODEX_HOME, 'hooks', 'credential-deny.mjs');
  const generatedHandler = `// Generated by vibecosystem from the allowlisted live credential-deny handler.\n${handlerSource}`;
  const commandHandler = {
    type: 'command',
    command: `${JSON.stringify(process.execPath)} ${JSON.stringify(handlerDest)}`,
  };
  for (const key of ['timeout', 'async', 'statusMessage', 'additionalContextLimit']) {
    if (Object.hasOwn(selected[0].source, key)) commandHandler[key] = selected[0].source[key];
  }
  const document = { hooks: { PreToolUse: [{ matcher: selected[0].allowed.matcher, hooks: [commandHandler] }] } };
  validateCodexHooks(document, generatedHandler);
  const hooksPath = join(CODEX_HOME, 'hooks.json');
  assertWritable(handlerDest, { marker: GENERATED_HOOK_MARKER });
  assertWritable(hooksPath);
  write(handlerDest, generatedHandler, { marker: GENERATED_HOOK_MARKER });
  write(hooksPath, `${JSON.stringify(document, null, 2)}\n`);
  return { events: 1, hooks: 1, candidates: Math.max(registered - 3, 1), excluded: Math.max(registered - 4, 0) };
}

// --- uninstall ---------------------------------------------------------------
// Removes only what this tool generated, identified by content, never by a
// blanket delete of the directory.
function uninstall() {
  const removed = { agents: 0, rules: 0, skills: 0, hooks: 0, hookState: 0, registry: 0 };
  const drop = (path) => {
    backupExistingPath(path);
    if (!DRY) rmSync(path, { recursive: true, force: true });
  };

  const agentDir = join(CODEX_HOME, 'agents');
  if (existsSync(agentDir)) {
    for (const f of readdirSync(agentDir).filter((x) => x.endsWith('.toml'))) {
      const p = join(agentDir, f);
      if (lstatSync(p).isSymbolicLink()) continue;
      if (readFileSync(p, 'utf8').startsWith(GENERATED_MARKER)) { drop(p); removed.agents++; }
    }
  }

  const agentsMd = join(CODEX_HOME, 'AGENTS.md');
  if (existsSync(agentsMd) && !lstatSync(agentsMd).isSymbolicLink() && readFileSync(agentsMd, 'utf8').startsWith(AGENTS_MD_MARKER)) {
    drop(agentsMd); removed.rules++;
  }

  if (existsSync(SKILLS_HOME)) {
    for (const d of readdirSync(SKILLS_HOME).filter((x) => x.startsWith('rule-'))) {
      const skillDir = join(SKILLS_HOME, d);
      const skillPath = join(skillDir, 'SKILL.md');
      if (lstatSync(skillDir).isSymbolicLink() || !existsSync(skillPath) || lstatSync(skillPath).isSymbolicLink()) continue;
      if (readFileSync(skillPath, 'utf8').includes(RULE_SKILL_MARKER)) {
        drop(skillDir); removed.skills++;
      }
    }
  }

  const hooksPath = join(CODEX_HOME, 'hooks.json');
  if (existsSync(hooksPath)) { drop(hooksPath); removed.hooks = 1; }
  const generatedHook = join(CODEX_HOME, 'hooks', 'credential-deny.mjs');
  if (existsSync(generatedHook) && readFileSync(generatedHook, 'utf8').startsWith(GENERATED_HOOK_MARKER)) {
    drop(generatedHook); removed.hooks++;
  }

  // Codex records a trusted_hash per hook entry; those keys outlive the file.
  const cfgPath = join(CODEX_HOME, 'config.toml');
  if (existsSync(cfgPath)) {
    let before = readFileSync(cfgPath, 'utf8');
    const registryStart = before.indexOf(REGISTRY_START);
    const registryEnd = before.indexOf(REGISTRY_END);
    if ((registryStart === -1) !== (registryEnd === -1)) throw new Error('Codex agent registry markers are incomplete in config.toml');
    if (registryStart !== -1) {
      before = `${before.slice(0, registryStart)}${before.slice(registryEnd + REGISTRY_END.length)}`;
      removed.registry = 1;
    }
    const after = before
      .split(/\r?\n/)
      .reduce((acc, line) => {
        if (/^\[hooks\.state(\.|\])/.test(line)) { acc.skip = true; acc.count++; return acc; }
        if (acc.skip) {
          if (/^\[/.test(line)) acc.skip = false;
          else return acc;
        }
        acc.out.push(line);
        return acc;
      }, { out: [], skip: false, count: 0 });
    removed.hookState = after.count;
    if (!DRY && (after.count || removed.registry)) {
      write(cfgPath, `${after.out.join('\n').replace(/\n{3,}/g, '\n\n').trim()}\n`);
    }
  }

  console.log(`  removed -> ${removed.agents} agent toml, ${removed.registry} agent registry, ${removed.rules} AGENTS.md, ${removed.skills} rule-* skills, ${removed.hooks} hook files, ${removed.hookState} [hooks.state] keys`);
  console.log('  kept    -> auth.json, model config, Codex bundled skills, session state');
}

// --- run --------------------------------------------------------------------
console.log(`codex-extras ${DRY ? '(dry-run)' : ''}`);
console.log(`  repo        ${REPO}`);
console.log(`  codex home  ${CODEX_HOME}`);
console.log(`  skills home ${SKILLS_HOME}`);
console.log(`  backup root ${BACKUP_ROOT}\n`);

if (flag('uninstall')) {
  uninstall();
} else {
if (ALL || flag('agents')) {
  const a = installAgents();
  console.log(`  agents  -> ${a.count} mirror TOML, ${a.overrides} overrides, ${a.excluded} excluded; luna_worker reserved`);
}
if (ALL || flag('rules')) {
  const r = installRules();
  console.log(`  rules   -> AGENTS.md ${(r.bytes / 1024).toFixed(1)} KB (${r.inline} guardrails), ${r.skills} rule-* skills, ${r.overrides} overrides`);
}
if (ALL || flag('hooks')) {
  const h = installHooks();
  console.log(`  hooks   -> ${h.hooks} across ${h.events} event; ${h.excluded}/${h.candidates} viable candidates excluded; trust pending`);
}
if (!ALL && !flag('agents') && !flag('rules') && !flag('hooks')) {
  console.log('  nothing selected. Pass --agents, --rules, --hooks, --all, or --uninstall.');
}
}
if (BACKUP_DIR) console.log(`  backup  -> ${BACKUP_DIR}`);
else if (DRY && BACKUP_PLANNED) console.log(`  backup  -> ${BACKUP_ROOT}/<timestamp>-<pid> (planned)`);
