/**
 * skill-curator.ts - Autonomous Skill Draft Curator
 *
 * SessionStart hook that reviews skill drafts generated by skill-compounder
 * and automatically promotes, merges, or archives them.
 *
 * Lifecycle:
 *   draft -> reviewed -> promoted (to ~/.claude/skills/)
 *         -> reviewed -> archived (to ~/.claude/skills-drafts/archive/)
 *         -> reviewed -> merged (consolidated with similar draft)
 *
 * Promotion criteria:
 *   - confidence >= 80
 *   - occurrences >= 3 OR category == 'error-recovery'
 *   - no existing skill with same pattern
 *
 * Archival criteria:
 *   - confidence < 50
 *   - or draft older than 14 days without promotion
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, renameSync, unlinkSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { reportHealth } from './shared/hook-health.js';

interface SessionEvent {
  type?: string;
  source?: string;
}

interface DraftMetadata {
  name: string;
  description: string;
  confidence: number;
  occurrences: number;
  category: string;
  status: string;
  generated_at: string;
  filepath: string;
}

const DRAFTS_DIR = join(homedir(), '.claude', 'skills-drafts');
const ARCHIVE_DIR = join(DRAFTS_DIR, 'archive');
const SKILLS_DIR = join(homedir(), '.claude', 'skills');

const PROMOTION_CONFIDENCE = 80;
const ARCHIVE_CONFIDENCE = 50;
const MAX_DRAFT_AGE_DAYS = 14;

function parseFrontmatter(content: string): Record<string, string> {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};

  const result: Record<string, string> = {};
  for (const line of match[1].split('\n')) {
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    const value = line.slice(idx + 1).trim().replace(/^"(.+)"$/, '$1');
    result[key] = value;
  }
  return result;
}

function loadDrafts(): DraftMetadata[] {
  if (!existsSync(DRAFTS_DIR)) return [];

  const drafts: DraftMetadata[] = [];
  try {
    const files = readdirSync(DRAFTS_DIR).filter(f => f.endsWith('.md'));
    for (const file of files) {
      const filepath = join(DRAFTS_DIR, file);
      try {
        const content = readFileSync(filepath, 'utf-8');
        const fm = parseFrontmatter(content);
        if (!fm.name) continue;

        drafts.push({
          name: fm.name,
          description: fm.description || '',
          confidence: parseInt(fm.confidence || '0', 10),
          occurrences: parseInt(fm.occurrences || '0', 10),
          category: fm.category || 'unknown',
          status: fm.status || 'draft',
          generated_at: fm.generated_at || '',
          filepath,
        });
      } catch { /* skip bad file */ }
    }
  } catch { /* no dir */ }

  return drafts;
}

function isDuplicateOfExisting(draft: DraftMetadata): boolean {
  if (!existsSync(SKILLS_DIR)) return false;

  try {
    const existingSkills = readdirSync(SKILLS_DIR).filter(f => {
      try {
        return statSync(join(SKILLS_DIR, f)).isDirectory();
      } catch { return false; }
    });

    // Exact name match
    if (existingSkills.includes(draft.name)) return true;

    // Similar category check - scan for existing patterns with same sequence
    for (const skill of existingSkills) {
      const skillFile = join(SKILLS_DIR, skill, 'SKILL.md');
      if (!existsSync(skillFile)) continue;
      try {
        const content = readFileSync(skillFile, 'utf-8');
        const fm = parseFrontmatter(content);
        // If both describe similar procedural pattern, count as dupe
        if (fm.category === draft.category && draft.description.length > 20) {
          const descWords = draft.description.toLowerCase().split(/\s+/).slice(0, 5);
          const existingDesc = (fm.description || '').toLowerCase();
          const overlap = descWords.filter(w => existingDesc.includes(w)).length;
          if (overlap >= 4) return true;
        }
      } catch { /* skip */ }
    }
  } catch { /* skip */ }

  return false;
}

function daysOld(timestamp: string): number {
  try {
    const then = new Date(timestamp).getTime();
    const now = Date.now();
    return (now - then) / (1000 * 60 * 60 * 24);
  } catch {
    return 0;
  }
}

function promoteDraft(draft: DraftMetadata): boolean {
  // Create skill directory
  const skillDir = join(SKILLS_DIR, draft.name);
  if (existsSync(skillDir)) return false;

  try {
    mkdirSync(skillDir, { recursive: true });

    // Read original draft and rewrite with promoted status
    const content = readFileSync(draft.filepath, 'utf-8');
    const promoted = content.replace(/status: draft/, 'status: active');

    writeFileSync(join(skillDir, 'SKILL.md'), promoted);

    // Remove from drafts
    try { unlinkSync(draft.filepath); } catch { /* skip */ }

    return true;
  } catch {
    return false;
  }
}

function archiveDraft(draft: DraftMetadata): boolean {
  try {
    mkdirSync(ARCHIVE_DIR, { recursive: true });
    const filename = draft.filepath.split('/').pop() || 'unknown.md';
    const archivePath = join(ARCHIVE_DIR, filename);
    renameSync(draft.filepath, archivePath);
    return true;
  } catch {
    return false;
  }
}

function runHook(): void {
  let input: string;
  try {
    input = readFileSync(0, 'utf-8');
  } catch { return; }

  let event: SessionEvent;
  try {
    event = JSON.parse(input);
  } catch { return; }

  const phase = event.source ?? event.type;
  if (phase !== 'startup' && phase !== 'resume') return;

  if (!existsSync(DRAFTS_DIR)) return;

  const drafts = loadDrafts();
  if (drafts.length === 0) return;

  let promoted = 0;
  let archived = 0;

  for (const draft of drafts) {
    // Archive low-quality drafts
    if (draft.confidence < ARCHIVE_CONFIDENCE) {
      if (archiveDraft(draft)) archived++;
      continue;
    }

    // Archive old drafts that never got promoted
    if (daysOld(draft.generated_at) > MAX_DRAFT_AGE_DAYS) {
      if (archiveDraft(draft)) archived++;
      continue;
    }

    // Promote high-confidence unique drafts
    if (draft.confidence >= PROMOTION_CONFIDENCE && !isDuplicateOfExisting(draft)) {
      if (promoteDraft(draft)) promoted++;
      continue;
    }

    // Otherwise leave in drafts for further review
  }

  if (promoted > 0 || archived > 0) {
    const parts: string[] = ['[skill-curator]'];
    if (promoted > 0) parts.push(`Promoted ${promoted} draft${promoted === 1 ? '' : 's'} to active skills.`);
    if (archived > 0) parts.push(`Archived ${archived} low-quality draft${archived === 1 ? '' : 's'}.`);

    console.log(JSON.stringify({
      systemMessage: parts.join(' '),
    }));
  }
}

const _start = Date.now();
try { runHook(); reportHealth('skill-curator', true, Date.now() - _start); } catch (e) { reportHealth('skill-curator', false, Date.now() - _start, e instanceof Error ? e.message : String(e)); process.exit(0); }
